modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "yetanotherchancebooster"
version = "${version}"
displayName = "YetAnotherChanceBooster"
authors = "gatekeep06"
description = '''
Server-side side-mod for Cobblemon, that allows you to boost spawn chances
'''
logoFile = "/assets/yetanotherchancebooster/icon.png"

[[dependencies.yetanotherchancebooster]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yetanotherchancebooster]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
